######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 23 20:25:00 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += thread.h threaddialog.h
SOURCES += main.cpp thread.cpp threaddialog.cpp
